baseurl = "/"
languageCode = "en-us"
disqusShortname = "miopulido" # Optional, enable Disqus integration
title = "Finance. Code. Comics"
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 3

[author]
    name = "Mio Pulido"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

[params]
    tagline = "Finance. Code. Comics."

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-0d"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "monokai"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Home"

    # Metadata used to drive integrations.
    googleAuthorship = "https://plus.google.com/+EmilioPulido"
    googleAnalytics = "UA-70453333-1"
    # gravatarHash = "MD5 hash of your Gravatar email address"

    # Sidebar social links, these must be full URLs.
    # github = "https://github.com/miopulido/"
    # bitbucket = "https://bitbucket.org/emili0/"
    # stackOverflow = ""
    # linkedin = ""
    googleplus = "https://plus.google.com/+EmilioPulido"
    # facebook = "https://www.facebook.com/miopulido"
    twitter = "https://twitter.com/MioPulido"
    # youtube = "https://www.youtube.com/channel/UCspsR1XmL1dl2kyoEjCUlOQ"

    # Other social-like sidebar links
    rss = false  # switch to true to enable RSS icon link
    # flattr = ""  # populate with your flattr uid
